---
esphome:
  name: test_light_strip
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passwd

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_passwd

# Enable logging
logger:

ota:
  password: !secret ota_passwd

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO23
    num_leds: 150
    rgb_order: GRB
    name: "Test LED Strip"
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:

# switch:
#   - platform: gpio
#     pin:
#       number: GPIO25
#       inverted: yes
#     name: "Test Relay"

binary_sensor:
  - platform: status
    name: "Test LED Strip Status"
